### ISSUE TITLE
dead links in documentation

### ISSUE THREAD

**Issue by jhahkala** [atos-ari-aeon/fiware-cloud-messaging-sdk#1]
Both the link to the technical documentation and to the quick start guide give application error from heroku.

**Comment by atos-ari-aeon** [comment]
Dear jhahkala,
The server on heroku is no longer available. You can use this ip to see the doc: http://130.206.116.137:3000/public/doc/html/apidoc/apidoc.html

Thanks for your comment!
Best,

Javier

**Comment by jhahkala** [comment]
Hi Javier,

I think you should update the readme.md to point to something that works. Currently when people look at the sdk here at Github, and click on the technical documentation link they just get the error page...

Cheers,
Joni

**Comment by atos-ari-aeon** [comment]
Hi Joni,
You are completely right ;) I already made the changes. I'll close the issue. If you have any comments, let me know.
Thanks!

**Comment by jhahkala** [comment]
Hi Javier,

ah, I see you updated the api component, but the links are also broken on this component, the sdk, and also on other components. 

Cheers,
Joni
